# Generated by Django 2.2.12 on 2020-04-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimages',
            name='query',
            field=models.SmallIntegerField(default=0, verbose_name='Kayan Fotoğraf Sırası'),
        ),
    ]
