# Generated by Django 2.2.12 on 2020-04-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200412_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='small_text',
            field=models.TextField(blank=True, null=True, verbose_name='Çarpıcı yazı. Eklenirse sol tarafta ayrı blok olarak gözükür.'),
        ),
    ]
